---

- name: create ec2 instance using ansible
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - "create_ec2"


- name: deploy the app on ec2 instance
  hosts: mediawiki
  gather_facts: yes
  become: yes
  roles:
    - "app_deploy"
